### ISSUE TITLE
catkin_make error: Multiple packages found with the same name 

### ISSUE THREAD

**Issue by won13y** [qboticslabs/mastering_ros#1]
I clone the repository of qboticslabs/mastering_ros
Afterward, I tried to catkin_make, but 

error is as following:

Multiple packages found with the same name

please let me know the problem!

wkyoun@wkyoun-XPS-13-9343:~/catkin_ws/src$ catkin_make

    Base path: /home/wkyoun/catkin_ws
    Source space: /home/wkyoun/catkin_ws/src
    Build space: /home/wkyoun/catkin_ws/build
    Devel space: /home/wkyoun/catkin_ws/devel
    Install space: /home/wkyoun/catkin_ws/install
    Multiple packages found with the same name "chefbot_bringup":
    - mastering_ros/chapter_9_codes/chefbot/chefbot/chefbot_bringup
    - mastering_ros/chapter_9_codes/chefbot/chefbot_bringup
    Multiple packages found with the same name "chefbot_description":
    - mastering_ros/chapter_9_codes/chefbot/chefbot/chefbot_description
    - mastering_ros/chapter_9_codes/chefbot/chefbot_description
    Multiple packages found with the same name "chefbot_gazebo":
    - mastering_ros/chapter_9_codes/chefbot/chefbot/chefbot_simulator/chefbot_gazebo
    - mastering_ros/chapter_9_codes/chefbot/chefbot_simulator/chefbot_gazebo
    Multiple packages found with the same name "diff_wheeled_robot_control":
    - mastering_ros/chapter_3_codes/diff_wheeled_robot_control
    - mastering_ros/chapter_4_codes/diff_wheeled_robot_control
    Multiple packages found with the same name "diff_wheeled_robot_gazebo":
    - mastering_ros/chapter_3_codes/diff_wheeled_robot_gazebo
    - mastering_ros/chapter_4_codes/diff_wheeled_robot_gazebo
    Multiple packages found with the same name "seven_dof_arm_config":
    - mastering_ros/chapter_10_codes/seven_dof_arm_config
    - mastering_ros/chapter_4_codes/seven_dof_arm_config
    Multiple packages found with the same name "seven_dof_arm_gazebo":
    - mastering_ros/chapter_10_codes/seven_dof_arm_gazebo
    - mastering_ros/chapter_3_codes/seven_dof_arm_gazebo
    - mastering_ros/chapter_4_codes/seven_dof_arm_gazebo
    Multiple packages found with the same name "seven_dof_arm_test":
    - mastering_ros/chapter_10_codes/seven_dof_arm_test
    - mastering_ros/chapter_4_codes/seven_dof_arm_test

**Comment by myyerrol** [comment]
I also clone this repository, and have the same problem. In addition, the mastering_ros_robot_description_pkg is empty. I think author can update it in the future.

**Comment by qboticslabs** [comment]
@myyerrol  @won13y  Guys, Sorry for the trouble. Actually you can understand from the error that, there are multiple packages on the different chapter folders. The repository is organized in a such a way that, each individual  packages need to copy to your R.O.S workspace. Not the complete chapters code. 

I have included same packages in different chapters because it is going with the flow of the book. I prefer to build the required package only. That can avoid this error !!

Thanks !! Keep posting your issues

**Comment by won13y** [comment]
@qboticslabs thank you, 

I erased the same package, and it works

**Comment by qboticslabs** [comment]
@myyerrol  Great !!!
