### ISSUE TITLE
robot don't move back.

### ISSUE THREAD

**Issue by intijk** [qboticslabs/mastering_ros#15]
In this code:

https://github.com/qboticslabs/mastering_ros/blob/master/chapter_3_codes/diff_wheeled_robot_control/scripts/diff_wheeled_robot_key
```
moveBindings = {
        'i':(1,0),
        'o':(1,-1),
        'j':(0,1),
        'l':(0,-1),
        'u':(1,1),
        ',':(-1,0),
        '.':(-1,1),
        'm':(-1,-1),
           }
```

It seems you use 'k' as stop, I suggest use 'k' to make it move backwardly and you already have space for stop :)

**Comment by qboticslabs** [comment]
For moving back you can use ',' or comma. Space or k is used to stop. This code actually adapted from turtlebot teleop node. You can check turtlebot teleop node too.
