### ISSUE TITLE
when I tring to lunch "seven_dof_arm_gazebo seven_dof_arm_gazebo_control.launch" it gave error as "IOError: [Errno 13] Permission denied: '/home/dhanu/.ros/rosdep/sources.cache/index'" 

### ISSUE THREAD

**Issue by dhanu2017** [qboticslabs/mastering_ros#16]
load_cached_sources_list with open(cache_index, 'r') as f:
IOError: [Errno 13] Permission denied: '/home/dhanu/.ros/rosdep/sources.cache/index'
spawn_model script started
[seven_dof_arm/controller_spawner-4] process has died [pid 13295, exit code 1, cmd /opt/ros/kinetic/lib/controller_manager/spawner joint_state_controller joint1_position_controller joint2_position_controller joint3_position_controller joint4_position_controller joint5_position_controller joint6_position_controller joint7_position_controller __name:=controller_spawner __log:=/home/dhanu/.ros/log/5d6b44f4-e78d-11e6-8eb3-9c5c8e0e9eb2/seven_dof_arm-controller_spawner-4.log].
log file: /home/dhanu/.ros/log/5d6b44f4-e78d-11e6-8eb3-9c5c8e0e9eb2/seven_dof_arm-controller_spawner-4*.log

**Comment by qboticslabs** [comment]
Hi Dhanu

I hope its a problem with your ROS installation. Just try to launch some other launch files and check its coming for that also.

Regards
Lentin Joseph
