### ISSUE TITLE
moveit_simple_grasps

### ISSUE THREAD

**Issue by kottesaikumar** [qboticslabs/mastering_ros#18]
@qboticslabs 
I am trying to run the command line "roslaunch seven_dof_arm_gazebo grasp_generator_server.launch",
I got a problem

[ERROR] [1465740328.774843123]: Grasp configuration parameter pregrasp_time_from_start missing from rosparam server. Did you load your end effector's configuration yaml file? Searching in namespace: /moveit_simple_grasps_server/right
[moveit_simple_grasps_server-2] process has died [pid 32558, exit code -11, cmd /home/hutlab/catkin_ws/devel/lib/moveit_simple_grasps/moveit_simple_grasps_server __name:=moveit_simple_grasps_server __log:=/home/hutlab/.ros/log/bc53a772-0493-11e7-b63f-c81f6631823d/moveit_simple_grasps_server-2.log].

**Comment by qboticslabs** [comment]
Can you try this package 

https://github.com/qboticslabs/mastering_ros/blob/master/chapter_10_codes/moveit_simple_grasps_1.zip

**Comment by wangjiwang** [comment]
> Can you try this package
> 
> https://github.com/qboticslabs/mastering_ros/blob/master/chapter_10_codes/moveit_simple_grasps_1.zip

I got the same problem. and I also use the moveit_simple_grasps_1.zip。 but it could not solve the problem. I am running this on Ubuntu 14.04.6, Ros indigo. Hoping to get your reply.

**Comment by wangjiwang** [comment]
> @qboticslabs
> I am trying to run the command line "roslaunch seven_dof_arm_gazebo grasp_generator_server.launch",
> I got a problem
> 
> [ERROR] [1465740328.774843123]: Grasp configuration parameter pregrasp_time_from_start missing from rosparam server. Did you load your end effector's configuration yaml file? Searching in namespace: /moveit_simple_grasps_server/right
> [moveit_simple_grasps_server-2] process has died [pid 32558, exit code -11, cmd /home/hutlab/catkin_ws/devel/lib/moveit_simple_grasps/moveit_simple_grasps_server __name:=moveit_simple_grasps_server __log:=/home/hutlab/.ros/log/bc53a772-0493-11e7-b63f-c81f6631823d/moveit_simple_grasps_server-2.log].

Did you solve this problem?
