### ISSUE TITLE
too many redundant codes

### ISSUE THREAD

**Issue by huiwenzhang** [qboticslabs/mastering_ros#34]
Hi,
If you clone all the codes and put them in the same catkin workspace, It will have errors cased by the redundancy, especially in chapter 2,3 ,4 and 10. So I am just wondering if there are some better ways to handle the redundancy except for compile them one by one. Or maybe you can delete the redundant code and make them  more compact. Thx!

**Comment by qboticslabs** [comment]
HI @huiwenzhang 
Sorry for that issue. What I intended was to show the progress of each package in each chapter. So you should be careful to pick the packages. If you want the package for the specific package, take the package from that chapter and put it in catkin_ws and do a catkin_make. 

Also if you want the final packages, i think you have to take the code from chapter 10.

**Comment by huiwenzhang** [comment]
Get it. Well, it does more clear to put all things in one package for each chapter so that they do not depend on each other.
