### ISSUE TITLE
Could not load controller 'joint_state_controller' because controller type 'joint_state_controller/JointStateController' does not exist

### ISSUE THREAD

**Issue by qboticslabs** [qboticslabs/mastering_ros#7]
Getting this error when executing the following command !! Page number 104 

$ roslaunch seven_dof_arm_gazebo seven_dof_arm_gazebo_control.launch

**Comment by qboticslabs** [comment]
Here is the solution !

Actually before running this launch file, please check  Page : 100 about different types of ROS controllers and the ROS package name. 

You should install this package manually. I didn't mention installation command  in that page ! 

If you want the installation commands, you can take the following commands


**$ sudo apt-get install ros-indigo-joint-state-controller  : This will install joint_state_controller package

$ sudo apt-get install ros-indigo-effort-controllers : This will install Effort controller

$ sudo apt-get install ros-indigo-position-controllers : This will install position controllers**

**Comment by ZhengQiushi** [comment]
thanks for your help!
