### ISSUE TITLE
demo_action_server.cpp

### ISSUE THREAD

**Issue by scottnortman** [qboticslabs/mastering_ros#8]
When running example code for actionlib client / server, the example from the book works as shown if the same arguments are passed, but if you change the client arguments to prevent preemption, the server issues a warning:

'Your executeCallback did not set the goal to a terminal status.  This is a bug in your ActionServer implementation.  Fix your code!

**Comment by qboticslabs** [comment]
@scottnortman  , I have fixed it, can you please clone it and try again. Changes are in demo_action_server.cpp only !!!

**Comment by scottnortman** [comment]
Different error after fix:

$ /demo_action succeeded at getting to goal 10 terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'

what():  boost thread:  trying joining itself:  Resource deadlock avoided Aborted( core dumped)

**Comment by qboticslabs** [comment]
Hi Scot

Can you send a screen cast of the error. Here it is working perfectly, i am giving a screen cast of working in my system. My mail id :qboticslabs@gmail.com

Please check :  [https://drive.google.com/file/d/0B1Tm9ca_m7pkV3hLcGhOU3VuTzA/view?usp=sharing ](url)

**Comment by scottnortman** [comment]
Hi

Issue solved.  When dealing with the prior issue I made a code change that I did not revert when you made the last fix.  All is working now.  Thanks again.
